function calculateSectionResistanceGUIDefaults(handles)

% Default Options
set(handles.LRFR_radiobutton,'value',1);
set(handles.LFR_radiobutton,'value',0);

% Default Inputs
inputs = {'Span Length, L',[];...
          'Max Unbraced Length, Lb',[];...
          'Steel Modulous, E',[];...
          'Steel Yield Strength, Fy',[];...
          'Concrete Strength, fc',[];...
          'Deck Thickness, ts',[];...
          'Effective Width, be',[];...
          'Haunch Depth, dh',[];...
          'Web Depth, dw',[];...
          'Web Thickness, tw',[];...
          'Top Flange Width, bf_top',[];...
          'Top Flange Thickness, tf_top',[];...
          'Bot. Flange Width. bf_bot',[];...
          'Bot. Flange Thickness, tf_bot',[];...
          'Non-Superimposed DL, wDL',[];...
          'Superimposed DL, wSDL',[];...
          'Wearing DL, wSDW',[]};
set(handles.Inputs_table,'Data',inputs)

end

